### ISSUE TITLE
Output URL

### ISSUE THREAD

**Issue by dominicholt** [chef/chef-server-cloudformation-templates#1]
First of all, thanks so much for putting this together. I'm having a slight problem. I've modified your template a bit as I'm on GovCloud, but the output URL looks something like this: https://ec2-96-127-62-4.us-gov-west-1.compute.amazonaws.com/ (I'm not sure if it's supposed to look like that, but either way I'm getting a connection rejected response). Any help you could provide would be most appreciated.

**Comment by juliandunn** [comment]
That looks correct. Does the template work on non-GovCloud regions?

**Comment by juliandunn** [comment]
Closing since no response.
